export const UNDELEGATION_BATCH = "UNDELEGATION_BATCH";
export const WITHDRAW_PROTOCOL = "WITHDRAW_PROTOCOL";
export const LS_CONTRACT_CONFIG = "LS_CONTRACT_CONFIG";
export const CONTRACTS_AND_POOLS = "CONTRACTS_AND_POOLS";
export const WALLET_BALANCES = "WALLET_BALANCES";
export const USER_HOLDING = "USER_HOLDING";
export const SP_GAS_ESTIMATE = "SP_GAS_ESTIMATE";
export const SP_PORTFOLIO_HOLDING = "SP_PORTFOLIO_HOLDING";
export const SP_PORTFOLIO_DEPOSIT_UNDELEGATE =
  "SP_PORTFOLIO_DEPOSIT_UNDELEGATE";
export const LS_TVL = "LS_TVL";
export const LS_HOLDING = "LS_HOLDING";
export const LS_BATCHES_HOLDING = "LS_BATCHES_HOLDING";
export const LS_AIRDROP = "LS_AIRDROP";
export const SP_STRATEGIES_CONTRACTS_AND_POOLS =
  "SP_STRATEGIES_CONTRACTS_AND_POOLS";
